server:
  port: 8181

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mscards
    username: postgres
    password: localdb

  jpa:
    show-sql: true

redis:
  server:
    urls: redis://localhost:6379

#feignClient
ms:
  user:
    base:
      url: http://localhost:9092/internal/api/v1/users